---
title: "HDT3"
output: html_document
date: '2022-08-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("forecast")
##install.packages("fUnitRoots")
#install.packages("ggfortify")

library(forecast)
library(tseries)
library(fUnitRoots)
library(ggfortify)
library(readxl)

library(keras)
library(tensorflow)
getwd()
df_consumo <- read_excel("./lstmdata/CONSUMO.xlsx", range="B7:G276")
```
```{r}
df_consumo
```

```{r}
df_importacion
```
```{r}
df_consumo$Diesel <- df_consumo$`Diesel alto azufre`+df_consumo$`Diesel bajo azufre`
df_consumo$`Diesel alto azufre` <- NULL
df_consumo$`Diesel bajo azufre` <- NULL
df_consumo[4] <- NULL
head(df_consumo)


summary(df_consumo)

```

```{r}


Consumo_super <- ts(df_consumo$`Gasolina superior`, start=c(2000, 1), frequency = 12)


plot(Consumo_super)


```
```{r}
dec_cons_super <- decompose(Consumo_super)
plot(dec_cons_super)
```


```{r}
dec_cons_Diesel <- decompose(Consumo_Diesel)
plot(dec_cons_Diesel)
```



```{r}
dec_imp_super <- decompose(importacion_super)
plot(dec_imp_super)
```

```{r}
plot(Consumo_super)
trans_cons_super<-diff(BoxCox(Consumo_super, 15))
plot(trans_cons_super)
acf(trans_cons_super)
adfTest(trans_cons_super)
```


```{r}


adfTest(Consumo_super)
adfTest(diff(Consumo_super))



## super
auto.arima(Consumo_super)

fit_consumo_super <- arima(log(Consumo_super), c(1, 1, 1),seasonal = list(order = c(2, 0, 0), period = 12))
forecastAP_Consumo_Super <- forecast(fit_consumo_super, level = c(95), h = 3*12)
autoplot(forecastAP_Consumo_Super)




```


```{r}

#SERIE consumo super CON LSTM

serie_norm <- scale(Consumo_super)
lagged<-c(rep(NA,1),serie_norm[1:(length(serie_norm)-1)])
supervisada <- as.data.frame(cbind(lagged,serie_norm))
colnames(supervisada)<-c("x-1","x")
supervisada[is.na(supervisada)]<-0

#length(Consumo_super)

cantidad_entrenamiento <- round(0.6*length(Consumo_super))
cantidad_validacion <- round(0.2*length(Consumo_super))
cantidad_entrenamiento
cantidad_validacion

#partimos en test, validacion y train. train las primeras 161 filas; validation las siguiente 54 filas y test las ultimas 54 filas.
test <-  tail(supervisada,cantidad_validacion)


supervisada<-supervisada %>% head(nrow(.)-cantidad_validacion)
validation<-supervisada %>% tail(cantidad_validacion)
supervisada<-head(supervisada,nrow(supervisada)-cantidad_validacion)
train<-supervisada

y_train <- train[,2]
x_train <- train[,1]
y_val <- validation[,2]
x_val <- validation[,1]
y_test <- test[,2]
x_test <- test[,1]
x_train



```

```{r}
paso <- 1
caracteristicas <-1
lote <-1
unidades <-  1

dim(x_train) <- c(length(x_train),paso,caracteristicas)
dim(y_train) <- c(length(y_train),caracteristicas)
dim(x_test) <- c(length(x_test),paso,caracteristicas)
dim(y_test) <- c(length(y_test),caracteristicas)
dim(x_val) <- c(length(x_val),paso,caracteristicas)
dim(y_val) <- c(length(y_val),caracteristicas)

plot(train)

modelo1 <-keras_model_sequential()
modelo1 %>% 
  layer_lstm(unidades, batch_input_shape=c(lote,paso,caracteristicas),
             stateful = T) %>%
  layer_dense(units = 1)
```



